package org.lm.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user
 *
 * @mbggenerated do_not_delete_during_merge
 */
@NoArgsConstructor
@Getter
@Setter
public class SysUser {
    /**
     * 用户 ID
     * id
     */
    private Long id;

    /**
     * 用户名
     * user_name
     */
    private String userName;

    /**
     * 密码
     * user_password
     */
    private String userPassword;

    /**
     * 邮箱
     * user_email
     */
    private String userEmail;

    /**
     * 创建时间
     * create_time
     */
    private Date createTime;

    /**
     * 简介
     * user_info
     */
    private String userInfo;

    /**
     * 头像
     * head_img
     */
    private byte[] headImg;



}